api:
  dashboard: true
  insecure: false

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: admin@backus.agency
      storage: /letsencrypt/acme.json
      tlsChallenge: {}

log:
  level: INFO
